# Generated by Django 4.2 on 2023-04-17 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='uid',
            new_name='id',
        ),
        migrations.AddField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(choices=[('MOV', 'Movie'), ('TVS', 'TV show')], default='MOV', verbose_name='type'),
        ),
    ]
