# Generated by Django 4.2 on 2023-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_personfilmwork_unique_person_id_film_work_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personfilmwork',
            name='unique_person_id_film_work',
        ),
        migrations.RemoveIndex(
            model_name='personfilmwork',
            name='person_idx',
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'genre'), name='unique_film_work_genre'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'person', 'role'), name='unique_film_work_person_id_role'),
        ),
    ]
